services:
  backend:
    command: sh -c "npm run start"
    build: ./backend
    ports: 
      - "4005:4005"
    volumes:
      - './backend/src:/app/src'
    env_file:
      - ./.db.env
    healthcheck:
      test: 
        - CMD-SHELL
        - 'curl -f http://backend:4005/graphql?query=%7B__typename%7D -H ''Apollo-Require-Preflight: true'' || exit 1'
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      db: 
        condition: service_healthy
  db:
    image: postgres
    restart: always
    env_file:
      - ./.db.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d cohesiobudget -U utilisateur"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - wmdatabase:/var/lib/postgresql/data
    environment:
      WDS_SOCKET_PORT: 8080
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

volumes:
  wmdatabase: {}
